/**
 * Code d'erreur stable envoyé au client en plus du `message` français —
 * permet au mobile de mapper vers un texte localisé plutôt que d'afficher
 * le message backend brut (préparation i18n ; une seule langue mappée pour
 * l'instant côté mobile, voir `error_messages_fr.dart`).
 */
export enum ErrorCode {
  // Générique / infrastructure — pas de sémantique métier propre.
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_FORBIDDEN_ROLE = 'AUTH_FORBIDDEN_ROLE',

  // Admin
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',

  // Agent
  AGENT_EMAIL_TAKEN = 'AGENT_EMAIL_TAKEN',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_NO_COMMUNE_ASSIGNED = 'AGENT_NO_COMMUNE_ASSIGNED',
  AGENT_COMMUNE_NOT_ASSIGNED_TO_AGENT = 'AGENT_COMMUNE_NOT_ASSIGNED_TO_AGENT',

  // Commune
  COMMUNE_NOT_FOUND = 'COMMUNE_NOT_FOUND',

  // Report
  REPORT_ALREADY_SUBMITTED = 'REPORT_ALREADY_SUBMITTED',

  // Device
  DEVICE_ID_MISSING = 'DEVICE_ID_MISSING',

  // Storage
  STORAGE_INVALID_IMAGE = 'STORAGE_INVALID_IMAGE',
  STORAGE_FILE_TOO_LARGE = 'STORAGE_FILE_TOO_LARGE',
  STORAGE_PURPOSE_NOT_ALLOWED = 'STORAGE_PURPOSE_NOT_ALLOWED',

  // Promo
  PROMO_NOT_FOUND = 'PROMO_NOT_FOUND',
  PROMO_NOT_OWNED_BY_COMMERCANT = 'PROMO_NOT_OWNED_BY_COMMERCANT',
  PROMO_DATE_FIN_NOT_FUTURE = 'PROMO_DATE_FIN_NOT_FUTURE',
  PROMO_DATE_FIN_EXCEEDS_MAX = 'PROMO_DATE_FIN_EXCEEDS_MAX',
  PROMO_ACTIVE_CAP_REACHED = 'PROMO_ACTIVE_CAP_REACHED',
  PROMO_ALREADY_PUBLISHED = 'PROMO_ALREADY_PUBLISHED',
  PROMO_NOT_PUBLISHED = 'PROMO_NOT_PUBLISHED',
  PROMO_PRIX_APRES_NOT_LOWER = 'PROMO_PRIX_APRES_NOT_LOWER',

  // Commercant
  COMMERCANT_PHONE_TAKEN = 'COMMERCANT_PHONE_TAKEN',
  COMMERCANT_NOT_FOUND = 'COMMERCANT_NOT_FOUND',
  COMMERCANT_PIN_ALREADY_SET = 'COMMERCANT_PIN_ALREADY_SET',
  COMMERCANT_NO_PENDING_REGISTRE_VERIFICATION = 'COMMERCANT_NO_PENDING_REGISTRE_VERIFICATION',
  COMMERCANT_NOT_IN_AGENT_COMMUNES = 'COMMERCANT_NOT_IN_AGENT_COMMUNES',
  COMMERCANT_TERMS_NOT_ACCEPTED = 'COMMERCANT_TERMS_NOT_ACCEPTED',
  COMMERCANT_REGISTRE_NOT_VALIDATED = 'COMMERCANT_REGISTRE_NOT_VALIDATED',
  COMMERCANT_REGISTRE_KEY_MISMATCH = 'COMMERCANT_REGISTRE_KEY_MISMATCH',
}
